ALTER TABLE users
  ADD COLUMN IF NOT EXISTS listing_fee_paid BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS listing_fee_paid_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS razorpay_payment_id VARCHAR(128) NULL;
